# Include the host/username/password for the test-servers
matrix:
  include:
  - os: linux
    language: python
    env:
      - SAB_NEWSSERVER_HOST=news.newshosting.com
      - SAB_NEWSSERVER_USER=sab-linux
      - secure: Ykqus/WexhnvvUZTW9Z3RNbTcU5y+htCeqOdOe18b7UfCbjVPsHty31zY4PMjawACT3eNetlSMJU2KkH6vE2z/cpEqe0Gejbz54zmS23+qtDnxDBbC8XaUkhvzV0s4fQIFuVLeIgV5wErfn+ayIT4Ez3IYZQqblTgVepXCfU6zAirr+70WLlwrs0EI5WtWgBVePhol79gFFUTST22RX/dW7Os2q+tAKj+a/aIm6u7LfdP0Tp8BuDhxVIBxytqenMr25MNoyQGMi6aHfe4h9wDuM2L2sBnkbOTU9g1v50D9eE+pCm/BDLyiM+4BMY5pbMdIe4YLtryvI6bPGg7g8tbnEE65aRvASpooSWzUP1R1+P5O9tDVE1RuEC1SK0wem5M8bzKNftAW3ZBsNXZ4tQ1MzlOSlW8nwd+R2ZEb2gXVEDNtuD30844EPVrfBAD9kgem1lDy51bkbHrNd4iKj9aaZ2bzyFkyJi0T4SgNM15sDUpVxohcUHj4n8L6esgnrc4iqhXCDMINnoiwD6sDsPAqp8cdsYtH5K03g47dxnlVT2XvKCAgFtG0eGuyAGs7tSa7fKIOtQCC7EU4P829FwcN2rcfEy0snbFYMetuhLNFZicpuy+X7JTVXLXmnQXHk+SkZfCH1AlQipy2wtJZjb8yHUZxGTH5a6aPfb0x7kfaI=
  - os: osx
    env:
      - HOMEBREW_NO_AUTO_UPDATE=1
      - SAB_NEWSSERVER_HOST=news.newshosting.com
      - SAB_NEWSSERVER_USER=sab-mac
      - secure: ttVp6oL+RswdN3AeeX+GrJmxQEgKc6QmimLesKSvWD5iio/yj3J8DzxdjwkHZUa5I7e5lk+IjVtIavqrNbYXxNKdKR3qU10XLnMkTuTYKocbaxAPaTJpp1tRfxeAsioLTQLRPEd/J3G6wcLWycvSWVu7+tq3kS/SniI9lyUNlvzsN0dALtmTtHfDnaF4kTsmdo+mupYpxZGU74NDlGqu+N+HCZrVQDMBxAV/WeKf8i7wpSQWWnFciJxpePuZ0SdMJKwxeocxaInEbAeRVWKCQiB07y7Sab2p1sYv4xujfOu7Ztv9rilOs8Ci1DUvaLD2WuxfD2dIV7Au2F//7yHUnoTSRGpDAg22Purgg1IxL1znII9cLOxytztMWv5dn64/u65cF5hub+xOB/ArtFX+jUU8TcyJ5H1fAIRTS3MU1CikkRLH5mYW1khsAFpPZ8QIfKBxLr5TUj/Ho1yf0m5gj/b1w6oa+ae0nAwnw4XVEZvA1qlH9k67UlEhRTav3ArV6ERquJRoshP+NIbQc9pXhrmbCXmxtk88sN5o3fIHK0MZpwCS1FIOjNck4OFqj3qA2lxXzkayvY+5qJ7Ekrtli5FYSnKcETm5wbF+ELRukFbe3DRwJCNYmrgLMZ636vjUTkDIkYVne7kW/nzvFprZB7yUvlQKWTgJ1A7VkBCrcQY=
    addons:
      chrome: stable

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew cask install chromedriver;
    else
      sudo add-apt-repository ppa:jcfp -y;
      sudo apt-get update -q;
      sudo apt-get install unrar p7zip-full par2 chromium-chromedriver -y;
      ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver;
    fi;

install:
  - pip install --upgrade -r tests/requirements.txt

script:
  - python ./tests/test_functional.py

notifications:
  email:
    on_success: never
    on_failure: always
